kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "jumpwire.fullname" . }}
  labels:
    {{- include "jumpwire.labels" . | nindent 4 }}
data:
  {{- if .Values.frontend.enabled }}
  {{- if .Values.frontend.secure }}
  JUMPWIRE_FRONTEND: wss://{{ .Values.frontend.host }}
  {{- else }}
  JUMPWIRE_FRONTEND: ws://{{ .Values.frontend.host }}
  {{- end }}
  {{- end }}
  {{- if .Values.aws.region }}
  AWS_REGION: {{ .Values.aws.region }}
  {{- end }}
  JUMPWIRE_DOMAIN: {{ .Values.domain }}
  LOG_LEVEL: {{ .Values.log_level }}
  VAULT_ADDR: {{ .Values.vault.address }}
  VAULT_KV_PATH: {{ .Values.vault.kv_path }}
  VAULT_DB_PATH: {{ .Values.vault.db_path }}
  {{- if .Values.environment }}
  JUMPWIRE_ENV: {{ .Values.environment }}
  {{- end }}
  {{- if .Values.sentry.dsn }}
  SENTRY_DSN: {{ .Values.sentry.dsn }}
  {{- end }}
  {{- if .Values.honeybadger.api_key }}
  HONEYBADGER_API_KEY: {{ .Values.honeybadger.api_key }}
  {{- end }}
  JUMPWIRE_CONFIG_PATH: /etc/jumpwire

  # List of other env variables, so far unused in this chart:
  #AWS_WEB_IDENTITY_TOKEN_FILE:
  #JUMPWIRE_CLOUDWATCH_ENABLED:
  #JUMPWIRE_CLOUDWATCH_INTERVAL_SECONDS:
  #JUMPWIRE_HTTP_PORT:
  #JUMPWIRE_HTTPS_PORT:
  #JUMPWIRE_MYSQL_PROXY_PORT:
  #JUMPWIRE_POSTGRES_PROXY_PORT:
  #JUMPWIRE_PROMETHEUS_PORT:
  #JUMPWIRE_STATSD_HOST:
  #JUMPWIRE_STATSD_PORT:
  #JUMPWIRE_STATSD_PREFIX:
  #JUMPWIRE_STATSD_SOCKET:
  #JUMPWIRE_STATSD_TYPE:
  #JUMPWIRE_TLS_PROXY_CA:
  #VAULT_KV_VERSION:
  #VAULT_SKIP_VERIFY:
---

kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "jumpwire.fullname" . }}-objects
  labels:
    {{- include "jumpwire.labels" . | nindent 4 }}
data:
  {{- (.Files.Glob .Values.configFile).AsConfig | nindent 2 }}
