{{- if .Values.ingress.enabled }}
{{- $fullName := include "jumpwire.fullname" . -}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
{{- $isManagedCertificateEnabled := and (eq .Values.cloud "gke") (.Values.gke.managedCertificate) }}
{{- $isFrontendConfigEnabled := and (eq .Values.cloud "gke") (.Values.gke.redirectHttps) }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "jumpwire.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    {{- if $isManagedCertificateEnabled }}
    networking.gke.io/managed-certificates: {{ $fullName }}-cert
    {{- end }}
    {{- if $isFrontendConfigEnabled }}
    networking.gke.io/v1beta1.FrontendConfig: {{ $fullName }}
    {{- end }}
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.domain | quote }}
      secretName: {{ $fullName }}-tls
  {{- end }}
  rules:
    - host: {{ .Values.domain | quote }}
      http:
        paths:
          - path: /
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ .Values.service.http }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ .Values.service.http }}
              {{- end }}
---
{{- if $isManagedCertificateEnabled }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ $fullName }}-cert
spec:
  domains:
    - {{ .Values.domain | quote }}
{{- end }}
---
{{- if $isFrontendConfigEnabled }}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: {{ $fullName }}
spec:
  redirectToHttps:
    enabled: true
{{- end }}
{{- end }}
