{{- $annotations := .Values.service.annotations -}}
{{- if eq .Values.cloud "gke" }}
  {{- if eq .Values.gke.neg "ingress" }}
    {{- $_ := set $annotations "cloud.google.com/neg" "{\"ingress\": true}" -}}
  {{- else if eq .Values.gke.neg "ports" }}
    {{- $_ := set $annotations "cloud.google.com/neg" "{\"exposed_ports\": {\"5432\": {}}}" -}}
  {{- else }}
    {{- $_ := set $annotations "cloud.google.com/neg" "{\"ingress\": false}" -}}
  {{- end }}

  {{- if eq .Values.service.type "LoadBalancer" }}
    {{- if .Values.service.external }}
      {{- $_ := set $annotations "cloud.google.com/l4-rbs" "enabled" }}
    {{- else }}
      {{- if and .Values.ingress.className (semverCompare ">=1.17-0" .Capabilities.KubeVersion.GitVersion) }}
        {{- $_ := set $annotations "networking.gke.io/load-balancer-type" "Internal" }}
      {{- else }}
        {{- $_ := set $annotations "cloud.google.com/load-balancer-type" "Internal" }}
      {{- end }}
    {{- end }}
  {{- end }}

{{- end }}
{{- if .Values.service.externalDns }}
  {{- $_ := set $annotations "external-dns.alpha.kubernetes.io/hostname" .Values.domain -}}
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jumpwire.fullname" . }}
  labels:
    {{- include "jumpwire.labels" . | nindent 4 }}
  annotations:
    {{- $annotations | toYaml | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.postgres }}
      targetPort: postgres
      protocol: TCP
      name: postgres
    - port: {{ .Values.service.mysql }}
      targetPort: mysql
      protocol: TCP
      name: mysql
    - port: {{ .Values.service.prometheus }}
      targetPort: prometheus
      protocol: TCP
      name: prometheus
  selector:
    {{- include "jumpwire.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jumpwire.fullname" . }}-cluster
  labels:
    {{- include "jumpwire.labels" . | nindent 4 }}
spec:
  type: {{ .Values.clusterService.type }}
  ports:
    - port: {{ .Values.clusterService.port }}
      targetPort: beam
      protocol: TCP
      name: beam
  selector:
    {{- include "jumpwire.selectorLabels" . | nindent 4 }}
