on:
  push:
    branches:
      - trunk
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - trunk

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/setup-kubectl@v1
      - run: helm lint

  package:
    runs-on: ubuntu-latest
    needs:
      - validate
    if: github.ref_type == 'tag'
    steps:
      - uses: actions/checkout@v2
      - uses: azure/setup-kubectl@v1
      - name: Configure GCP auth
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      - run: helm plugin install https://github.com/hayorov/helm-gcs.git

      - name: Create chart archive
        run: helm package .
      - name: Upload chart
        run: |
          helm repo add jumpwire gs://charts.jumpwire.ai
          helm gcs push jumpwire-*.tgz jumpwire --public --publicUrl https://charts.jumpwire.ai/ --retry
